apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: mycrd-sparkop-nonscheduled-pi
  namespace: batchpy
spec:
  image: "harbor.my.org:1080/base/py/pyspark"
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      app: sparkop-nonscheduled-pi
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      app: sparkop-nonscheduled-pi
