apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: ScheduledSparkApplication
metadata:
  name: mycrd-sparkop-scheduled-pi
  namespace: batchpy
spec:
  template:
    schedule: "@every 5m"
    image: "harbor.my.org:1080/base/py/pyspark"
    mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
    driver:
      cores: 1
      coreLimit: "1200m"
      memory: "512m"
      labels:
        app: sparkop-scheduled-pi
    executor:
      cores: 1
      instances: 1
      memory: "512m"
      labels:
        app: sparkop-scheduled-pi
