apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy-usertestsys-vocabularysizeestimation-test
  namespace: servpy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usertestsys-vocabularysizeestimation-test
  template:
    metadata:
      labels:
        app: usertestsys-vocabularysizeestimation-test
    spec:
      containers:
        - image: harbor.my.org:1080/python-app/usertestsys-vocabularysizeestimation:latest
          envFrom:
            - configMapRef:
                name: "usertestsys-test"
          name: usertestsys
          resources:
            limits:
              cpu: "2"
              memory: 6Gi
            requests:
              cpu: "1"
              memory: 3Gi

