apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  namespace: servpy
spec:
  template:
    spec:
      affinity:            #亲和性
        nodeAffinity:        #node亲和性
          # 硬亲和性限制
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname # 标签键名
                    operator: In      #键值运算关系 ，NotIn:label的值不在某个列表中。 表示不是node02节点就可运行
                    values:
                      - hadoop-pre001 # 标签键值
