apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../base/usertestsys/overlays/usertestsys-speakingevaluation
patchesStrategicMerge:
- deployment_patch.yaml
commonAnnotations:
  manual_redeploy: 2021-03-12-17-22
images:
- name: harbor.my.org:1080/python-app/usertestsys-speakingevaluation
  newTag: "20210429165452_615"
