apiVersion: v1
kind: PersistentVolume
metadata:
  name: mvn-m2-nfs-pv
  labels:
    storage: mvn-nfs-pv
  annotations:
    kubernetes.io.description: pv-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  mountOptions:
    - vers=4
  nfs:
    path: /data/cdhdata1/bigopera/nfs-mvn
    server: 192.168.0.62
