kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mvn-m2-pvc
  namespace: default
  labels:
    storage: mvn-nfs-pvc
  annotations:
    kubernetes.io/description: "PersistentVolumeClaim for PV"
spec:
  selector:
    matchLabels:
      storage: mvn-nfs-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: nfs
  resources:
    requests:
      storage: 8Gi
