apiVersion: v1
kind: PersistentVolume
metadata:
  name: pypi-nfs-pv
  labels:
    storage: pypi-nfs-pv
  annotations:
    kubernetes.io.description: pv-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  mountOptions:
    - vers=4
  nfs:
    path: /data/cdhdata1/bigopera/pypi/codekoala
    server: 192.168.0.62
